### ISSUE TITLE
논문 초안 관련 질문

### ISSUE THREAD

**Issue by orangeswu** [yeongyeongkim/pbl5_team7#17]
논문 초안 내용 중 **밴되는 부분**이 전반적으로 잘 이해가 되지 않아 질문드립니다.

- 앱 리스트를 서버로 보내서 밴된 기능 받아오기 
      -> Q1. 여기서 의미하는 벤된 기능이 무엇인가요? 설치된 앱이 요구한 권한들 중 거부된 권한들일까요?

- 몇 % 이상 밴되었는가? // 사용자 커스텀 가능
  -> Q2. 몇 %를 판단하는 기준은 무엇인가요? 예를 들어, 각 앱(카카오톡)에서 요구하는 권한(마이크, 위치, 저장공간 등) 중 거부된 권한의 비율인가요? 그렇다면, 한 앱마다 비율을 설정하는 것일까요?

- view의 on/off auth status 중
  -> Q3. 'auto: 설정한 banned ratio에 따라 자동 동기화 (default)' 부분이 의미하는 바가 한 앱의 권한들 중 설정한 거부된 비율에 맞춰서 자동으로 권한이 거부된다는 것일까요? 그렇다면 민감한 권한 순으로 거부가 되는 것일까요?

**Comment by yeongyeongkim** [comment]
첫 질문 감사합니다.
일단 질문하신 사항에 아래와 같이 답변해드리되, 추가 질문이 있으시면 언제든 자유롭게 질문해주세요!

>   논문 초안 내용 중 밴되는 부분이 전반적으로 잘 이해가 되지 않아 질문드립니다.
>   
>   앱 리스트를 서버로 보내서 밴된 기능 받아오기
>   -> Q1. 여기서 의미하는 벤된 기능이 무엇인가요? 설치된 앱이 요구한 권한들 중 거부된 권한들일까요?

네 맞습니다.


> 몇 % 이상 밴되었는가? // 사용자 커스텀 가능
> -> Q2. 몇 %를 판단하는 기준은 무엇인가요? 예를 들어, 각 앱(카카오톡)에서 요구하는 권한(마이크, 위치, 저장공간 등) 중 거부된 권한의 비율인가요? 그렇다면, 한 앱마다 비율을 설정하는 것일까요?

앱의 각 권한마다 거부된 비율입니다.
예를 들어 앱 A에 b c d라는 권한이 있고,
여러 사용자들에게 b가 30% 거부, c가 50% 거부, d 가 70% 거부되었다고 할 때
사용자가 60% 이상 거부한 권한들을 나도 거부하겠다라고 설정을 하면 권한 d만 거부될 것입니다.

> view의 on/off auth status 중
> -> Q3. 'auto: 설정한 banned ratio에 따라 자동 동기화 (default)' 부분이 의미하는 바가 한 앱의 권한들 중 설정한 거부된 비율에 맞춰서 자동으로 권한이 거부된다는 것일까요? 그렇다면 민감한 권한 순으로 거부가 되는 것일까요?

Q2와 같습니다. default가 아닌 사항은, 사용자가 직접 해당 권한을 활성화/비활성화 했다고 간주되는 권한들입니다.
