### ISSUE TITLE
merge

### ISSUE THREAD

**Issue by thdwls** [yeongyeongkim/pbl5_team7#19]
`question` merge 파트에 대한 확인 질문

제가 생각했던 merge 파트의 역할은 SQL, UI의 코드가 완성되면 해당 코드들이 연동할 수 있도록 합치고 놓친 파트들을 점검 및 추가 코딩 및 완성이라고 생각했는데요. 파트에 대해 제가 잘못 이해하고 있는게 있거나, 추가적으로 언급할 사항이 있으면 말해주세요.

**Comment by yeongyeongkim** [comment]
직접 업로드 하신 코드에 대해서 개별적으로 리뷰 받고 머지 받으면 될 것 같아요. 브랜치를 따로 파서 pull request를 날려주세요.
