### ISSUE TITLE
논문 관련 논의

### ISSUE THREAD

**Issue by yeongyeongkim** [yeongyeongkim/pbl5_team7#24]
교수님 피드백에 대해서 논의사항 공유합니다.

1. 논문 전문 상 참고문헌
[4] Permission Explorer, https://github.com/ruippeixotog/permission-explorer
[] CWE-250: Execution with Unnecessary Privileges
[] 유홍렬, 권태경. (2014). 안드로이드 권한의 위험을 판단하기 위한 평가척도에 관한 연구. 한국정보과학회 학술발표논문집, (), 1009-1011.
를 어디에 삽입해야 자연스러울까요?

2. 논문상 리스트화 된 프로그램 스펙 중 한글화하거나 문장화 할 수 있는 부분이 있나요?

**Comment by yeongyeongkim** [comment]
논문 양이 많아서 두 줄 정도만 추가해도 5페이지가 되어서 이 부분 참고하시고 의견 부탁드립니다.

**Comment by thdwls** [comment]
### (영문)논문제목
* 전치사, 접속사를 제외한 모든 단어의 첫 글자는 대문자로 시작
-> __Android App Permission Detection and Management Automation System__

### 인적사항 수정 요청
* `e-mail`

### 맞춤법
* `서론` 허용여부 -> 허용 여부
* `본론` 모아온다 -> 모아 온다
* `본론` 목록을불러온다 -> 목록을 불러온다

### 표현의 보완
* `결론` 따라서 향후 사람이 개입되지 않고 정확하게 '이것이 과도한 권한인가'에 대한 판단을 하는 알고리즘을 머신러닝을 통해서 구현하고 추가할 계획이다.
-> 따라서 향후 머신러닝을 통해 사람의 개입 없이도 '이것이 과도한 권한인가'를 판단하는 정확성 높은 판별 알고리즘을 추가 구현할 계획이다.

### 기타
* 목차를 제외한 본문 내용의 폰트가 바탕, 굴림, 그 외 영문 폰트가 혼용되어 있는 것으로 확인됩니다. 작년 학술대회 논문을 살펴보면, 어떤 종류의 폰트를 사용하는지는 크게 중요하지 않아 보이지만 본문내용의 폰트는 동일하게 적용하면 좋을 듯 합니다.

**Comment by yeongyeongkim** [comment]
수정 부분 모두 반영해서 재제출했습니다.
